### ISSUE TITLE
No folder creation to store the settings

### ISSUE THREAD

**Issue by LaGlobule** [wokhan/WFN#121]
When launching WFN.exe for the first time, the settings can't be saved neither the firewall configuration because the default path "...AppData\Local\Wokhan Solutions\WFN" does not exist. IMHO, it should be created at first start of WFN.exe. 
WFN 2.5.370.0 Amd64 on W10 20H2

**Comment by GregZero** [comment]
Same issue here, neither unable to change option settings for portable mode

**Comment by wokhan** [comment]
Thank you both! I'll check that next week (won't be able before unfortunately). Fixing it should be easy though 😊

**Comment by wokhan** [comment]
Hi, I wasn't able to work on this project lately, sorry, so the issue is still here.
In the meantime, creating the folder manually is the only possible workaround (but I guess you already did 🤔😅).

**Comment by GregZero** [comment]
> ...please consider creating the folder manually,...
Hi,
for my case, I will try that for test purpose only. Because in portable mode it can't be the way :-)

**Comment by GregZero** [comment]
Ok,
So : After creating the App User local folder; saving is ok.
Then, by choosing "portable mode" the setting file is correctly created (moved, precisely) in the portable directory.
Thank you.
