### ISSUE TITLE
Settings.json problem

### ISSUE THREAD

**Issue by StefanoAlonso** [wokhan/WFN#124]
'Apply' does not work, I have info that settings.json file is missing (check attachment). Basically, the whole folder Wokhan Solution from AppData is missing. I opened WFN as Admin and still not working. Hope this makes sense ;)
WFN sits here: C:\ProgramData\Windows Firewall Notifier (Program Files at my PC need Admin privileges).

![Screenshot 2021-01-25 155424](https://user-images.githubusercontent.com/14233182/105714977-b3ce4300-5f25-11eb-81b9-a7f2d95a07dd.png)

**Comment by wokhan** [comment]
Hi, this is a dup of issue #121. In the meantime please consider creating the folder manually, and sorry about this noob mistake I made 😅
