### ISSUE TITLE
Allow collapsing monitor / connection table by app

### ISSUE THREAD

**Issue by AFlowOfCode** [wokhan/WFN#140]
Hi, first of all I really like this utility & I've been looking for something like this for a while. You've done a good job making something simple and useful. 

I have one comment / request which I think would make viewing active connections quicker and easier - allow clicking on the app title in the monitoring table to collapse (hide) all that app's connections & instead show a number that simply tells you how many there are. This way you could quickly note which apps have open connections without needing to scroll all the way to the bottom past every single connection detail for every app to make sure you've seen all apps or manually count each connection row. 

![WFN table](https://user-images.githubusercontent.com/14116237/140951608-a47bd223-f6eb-42d9-9c2c-47452906d053.PNG)

To illustrate, in above example you'd click on the blue line "chrome.exe (Google Chrome)", it would hide the specific connection & show "chrome.exe (Google Chrome) (1)" to summarize number of connections instead of showing them. Clicking on firefox.exe line would then collapse and show "firefox.exe (Firefox) (2)", etc.

**Comment by wokhan** [comment]
Hi, thank you for your feedback! 

I'll add this to the requested features list since it could be useful (as usual, no ETA as I've limited free time, actually partly used for another project I'd like to publish on GitHub soon!).
