### ISSUE TITLE
WFNlite

### ISSUE THREAD

**Issue by hoasis2** [wokhan/WFN#143]
Dear @AtlasHackert 
would you mind releasing an executable of [WFNlite](https://github.com/AtlasHackert/WFNLite/releases)? :-)

I apologize if this request is not appropriate!

**Comment by AtlasHackert** [comment]
I don't see why? I never really got anywhere with it: currently it's just an old version of WFN with Console.exe removed. I was planning on simplifying and streamlining the code, but never got around to doing that.

**Comment by hoasis2** [comment]
I see, thank you for the clarification.
