### ISSUE TITLE
cannot locate resource /ui/themes/.xaml

### ISSUE THREAD

**Issue by AFlowOfCode** [wokhan/WFN#147]
Hello, I'm looking forward to trying out the new nightly version! 

However when I try to run it I get the titular error "Cannot locate resource /ui/themes/.xaml". In fact it pops up two error dialogs stating the same thing. I created the same path to a dummy file from the executing directory, but it didn't work. I'm not sure where it is looking for this file.

**Comment by wokhan** [comment]
Hi, 

Thanks for you enthusiasm 😊

There is indeed an issue with this nightly when it's launched at first. I'll give it a look right now.
The said "missing" file is an embedded resource: a new feature allows to pick a theme (dark/light/automatic/system colors) but wrongly attempts to load an empty one in some cases (hence the ".xaml" file extension without a proper name).

**Comment by wokhan** [comment]
New nightly build in progress 😉

**Comment by wokhan** [comment]
Done, you can head to the "nightly" release page and pick the latest build (or simply click here: [x86](https://github.com/wokhan/WFN/releases/download/nightlies/wfn-x86-full-nightly-no-test-20230103-39d0cb.zip) / [x64](https://github.com/wokhan/WFN/releases/download/nightlies/wfn-x64-full-nightly-no-test-20230103-39d0cb.zip))

**Comment by AFlowOfCode** [comment]
Excellent, thank you!
