### ISSUE TITLE
Error when saving options

### ISSUE THREAD

**Issue by Arkewas** [wokhan/WFN#149]
Hello,

I have installed WFN portable from  wfn-x64-standalone-v2.5-beta.zip 

I changed the option to start WFN minimized but when I click on the button to save options  I get the error message:

"Object reference not set to an instance of an object."

The same error occurs when I click also on buttons "cancel" or "reset to default" so close option window I have to terminate wfn.exe process.

My OS is Windows 11 21H2 Build 22000.1335

Thank you

**Comment by wokhan** [comment]
Hi,
Thank you for your feedback, checking now ;-)

**Comment by wokhan** [comment]
Glad to hear this! Thanks and feel free to tell if you have any request or concerns.
