### ISSUE TITLE
Error on saving settings, have to create settings directory and file manually [bug]

### ISSUE THREAD

**Issue by selivan** [wokhan/WFN#155]
WFN version: 2.5 Beta
Windows version: 11 22H2

![image](https://user-images.githubusercontent.com/1208989/224336607-317c8c96-d9e3-4433-a86f-5bb79918e4f7.png)

WPF is running with elevated privileges.

Error appears while trying to save settings. Portable mode is not enabled.

Error is fixed when I manually create directory and file mentioned in the error message.

**Comment by wokhan** [comment]
Hi! Sorry about this bug, it has been fixed in the nightlies months ago but I didnt "advertise" it. You can give it a try, I'll publish them as beta soon since they seem to be stable enough. 

Duplicate of #149

**Comment by selivan** [comment]
In latest nightly ( wfn-20230312-c0ea1e-x64-standalone.zip ) works fine.
