### ISSUE TITLE
Security log screen is empty [bug]

### ISSUE THREAD

**Issue by selivan** [wokhan/WFN#157]
WFN version: 2.5 Beta
Windows version: 11 22H2
![image](https://user-images.githubusercontent.com/1208989/224337966-1f5aa208-6eb2-41a0-ad5a-cbdfaeb963fd.png)

**Comment by wokhan** [comment]
Hi (again 😉), thanks for your feedback. Could you please check with the latest nightly if the same occurs?
Thanks

**Comment by selivan** [comment]
I'll check it. Where can I get the latest nightlies build? Github releases page offers nightlies from 2020  and 2.5 Beta from 2021.

**Comment by wokhan** [comment]
There is an issue (or is it?) with the release page where the date is related to when it has been created, not updated... If you seek through the offered packages, you'll see that some of them are more recent (last week or so). Those ones are the latest, you can pick the version that applies for you there. 
I cannot direcly link from there as I'm on my phone (well I can but I won't yet 😁), but I'll check if there is a way to get the latest version in the readme automatically.
Thanks

**Comment by selivan** [comment]
In latest nightly ( wfn-20230312-c0ea1e-x64-standalone.zip ) works fine.
