### ISSUE TITLE
Issues with the system theme

### ISSUE THREAD

**Issue by UltimateEvil** [wokhan/WFN#160]
Ran into some exceptions which gives you no info what so ever in the alpha release. 

But by downloading the source code, compiling as debug and running in visual studio I got it down to

BandwidthGraph.xaml.cs
```
    private void InitAxes()
    {
var skAxisPaint = new SolidColorPaint(((SolidColorBrush)Application.Current.Resources[SystemColors.WindowTextBrushKey]).Color.ToSKColor());

```
Application.Current.Resources[SystemColors.WindowTextBrushKey] is null here for whatever reason.

Band-aid solution which is probably not dynamic
`new SolidColorPaint((SystemColors.WindowTextBrush).Color.ToSKColor());`

**Comment by wokhan** [comment]
Hi (again) 😄 
Thanks! Indeed the dynamic part is useful (for the new theming feature) so I'd like not remove it, but still it's weird it's failing randomly. Looking at this now.

**Comment by wokhan** [comment]
Wild guess: the Ressources dictionary is accessed too soon, so I moved the Axes initialization in a Loaded event handler.
Since this is random, I'll push this "fix" as-is and will revert if it's not OK (I'll check your other issues first).

**Comment by UltimateEvil** [comment]
@wokhan 
Pulled the latest changes, built the master branch and unfortuanately this did not resolve the issue.
Still getting a `Object reference not set to an instance of an object.` exception. The `Application.Current.Resources[SystemColors.WindowTextBrushKey]` object seems to be consistently null for the system theme. Not for any of the others, though

**Comment by wokhan** [comment]
Thanks! I guess I didn't reproduce this properly. Now that you nailed the specific case, I'll give this another try.
