### ISSUE TITLE
Error Displaying On Map "Invalid Credentials. Sign up for a developer account at: http://www.microsoft.com/maps/developers"

### ISSUE THREAD

**Issue by scramblr** [wokhan/WFN#165]
Today I started noticing an error that says 
```'"Invalid Credentials. Sign up for a developer account at: http://www.microsoft.com/maps/developers"'```

I'm guessing this is because there's a hard-coded API key for the maps to be drawn, but I don't see any obvious place in the UI to change the key. Is there a place where we can change the API key to use a personal one that presumably would re-enable the maps again? 

Also, since I'm guessing this is going to quickly become more and more of a "thing" because this project is growing, I might suggest that the ability to change map providers be an option. For instance, MapBox is a free solution that I've seen used in a lot of places and is completely free for personal use. Maps.Me is also very cool, and doesn't need to be paid for AFAIK unless you need the special features like where to find a close-by drinking fountain ;). 

Here's a screenshot of my error if interested..
![WFN maps error](https://github.com/wokhan/WFN/assets/52064980/d1099fa0-db1d-4038-a253-c617154d8a02)

https://notdan.org/wp-content/uploads/2024/06/WFN.maps_.error_.png

**Comment by wokhan** [comment]
Hi, thanks for your feedback! Bing maps changed its policy so it might be related, anyway you're right, we should switch to another provider or let the user pick one. I'll check that (as usual, no ETA 😅 It's an easy fix though!).
Have a nice day

**Comment by wokhan** [comment]
Hi, FYI, I'm working on it, using another map control (mapsui.com). I had also some other improvements I forgot about (oops), so it's not as straightforward as it could have been 😄

**Comment by wokhan** [comment]
For those interested, here is what it looks like tonight with MapsUI, including the UI/UX improvements I was mentionning (and which are not related to this issue).
So far it works pretty well, I still have to work on the symbols and tooltips on the map.

<img width="1159" alt="Capture d’écran 2024-07-06 233354" src="https://github.com/wokhan/WFN/assets/24826061/c3809128-b527-4def-8deb-e891b8a79232">

**Comment by wokhan** [comment]
Progress for today: connection selection in the list now reflects on the map ; hovering a location displays the same tootip as before ; performance and stability seem OK.
A few bugs fixes / improvements and I'll push a new nightly soon 🥳

**Comment by wokhan** [comment]
Hi @scramblr  & all, a new nightly has been published (not totally done but it can be tested "as-is").
I also updated the Connections list logic and improved some other parts - I'll keep working on it during the summer ;-)

**Comment by scramblr** [comment]
You are amazing - **THANK YOU** for all of the hard work and dedication, it truly is appreciated and I hope you realize how much all of the work being done on this is appreciated by so many. Take care!

**Comment by wokhan** [comment]
Thank you very much for this nice message, it makes me really happy and motivates me even further 😊 I'm closing this issue, feel free to tell if there is anything I can improve (while I know there are still some bugs or inconsistencies to fix - working on it! -, I probably miss some of those as well!).
